
version: 2

dependencies:
  override:
    - yarn
test:
  override:
    - yarn test

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/laravel

    steps:

      - checkout

      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-

      - run: composer install -n --prefer-dist
      - run: ./vendor/bin/phpunit
      - run: npm run dev
