
version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/laravel
    steps:
      - checkout

      - run:
        name: Install sqlite
        command: sudo apt install -y libsqlite3-dev zlib1g-dev

      - run:
        name: docker php extension
        command: sudo docker-php-ext-install zip

      - run:
        name: Update composer
        command: sudo composer self-update

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-

      - run:
        name: composer install
        command: composer install -n --prefer-dist


      - run:
        name: run phpunit
        command: ./vendor/bin/phpunit
